language: rust
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
  allow_failures:
    - rust: nightly

dist: trusty
script:
- scripts/build.sh
deploy:
  - provider: s3
    skip_cleanup: true
    bucket: files.gridbugs.org
    region: ap-southeast-2
    local-dir: uploads
    acl: public_read
    on:
      all_branches: true
      repo: stevebob/meters-below-the-ground
      condition: "$TRAVIS_RUST_VERSION = stable"
    access_key_id: AKIAJTZWT26OECTU2UVQ
    secret_access_key:
        secure: P/Izz6Ef3eUD6yI7p2/IKRrXvVvUC5oBhu3NiPEYl9FOunmF7kk+V1ZuQm5KvHV3Y+n3ZP6WYPrHDVtxiKPS12xArt3MvUd8ssaNQvkNTwiqy16y3REElj0KiTYXHf9XDw2WBCp+E5UZ4kEdfNrWTtHEqmc6KMPp4ySVVHOPu81GV2bPOgNWC/QwUnqKUYW1y9CbcEA+MQWZCDXyb7HYl2+4tatj+V9Sz60UBeMZwYDXHtz+VdOLLmQKbfo81WiQ7HuNmd/0kg/Wu6Vq1dHjtUsl/14RjcHA/Z+ZyWdTBSxo/8JY6jVyjiPlGjBTABt14GzeScrZKnYP7XTXfv3AKrMnR2ItNDA6D5yOEYvYKRl1oPDM9vy92RPzw1nXivJ+IljNLNKmgWh2Vo8njMIb0buOyQmtoqy8lq9s/yA1jS9BsrrkODIECv40xrJeUb39I8bj1/tLzlPA3RHUd05kmTEFfiIAlJU5K7x7ko4Hub3blJfFKcR/kce2CUqRErhH0M6ZyPXayzCaSLwwPX1hF0d8HCGTIA7b3xmej6otbAFSQI2njD1ju2lYdftxo11rxt/PEDszUa3BCuoPFr4cu3sasI7tt4tuioNdxpFndUu/A58DdZ0tpcmFj+5hRabbYNFbfCwTes+b/LJCEuHqZdKfNgNGGVC/HrsaAozydHk=
  - provider: s3
    skip_cleanup: true
    bucket: games.gridbugs.org
    region: ap-southeast-2
    local-dir: web_uploads
    acl: public_read
    on:
      all_branches: true
      repo: stevebob/meters-below-the-ground
      condition: "$TRAVIS_RUST_VERSION = beta"
    access_key_id: AKIAJTZWT26OECTU2UVQ
    secret_access_key:
        secure: P/Izz6Ef3eUD6yI7p2/IKRrXvVvUC5oBhu3NiPEYl9FOunmF7kk+V1ZuQm5KvHV3Y+n3ZP6WYPrHDVtxiKPS12xArt3MvUd8ssaNQvkNTwiqy16y3REElj0KiTYXHf9XDw2WBCp+E5UZ4kEdfNrWTtHEqmc6KMPp4ySVVHOPu81GV2bPOgNWC/QwUnqKUYW1y9CbcEA+MQWZCDXyb7HYl2+4tatj+V9Sz60UBeMZwYDXHtz+VdOLLmQKbfo81WiQ7HuNmd/0kg/Wu6Vq1dHjtUsl/14RjcHA/Z+ZyWdTBSxo/8JY6jVyjiPlGjBTABt14GzeScrZKnYP7XTXfv3AKrMnR2ItNDA6D5yOEYvYKRl1oPDM9vy92RPzw1nXivJ+IljNLNKmgWh2Vo8njMIb0buOyQmtoqy8lq9s/yA1jS9BsrrkODIECv40xrJeUb39I8bj1/tLzlPA3RHUd05kmTEFfiIAlJU5K7x7ko4Hub3blJfFKcR/kce2CUqRErhH0M6ZyPXayzCaSLwwPX1hF0d8HCGTIA7b3xmej6otbAFSQI2njD1ju2lYdftxo11rxt/PEDszUa3BCuoPFr4cu3sasI7tt4tuioNdxpFndUu/A58DdZ0tpcmFj+5hRabbYNFbfCwTes+b/LJCEuHqZdKfNgNGGVC/HrsaAozydHk=
