language: rust
matrix:
  include:
  - os: linux
    rust: stable
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
  - os: osx
    rust: stable
  allow_failures:
  - rust: nightly
dist: trusty
deploy:
  provider: s3
  access_key_id: AKIAJTZWT26OECTU2UVQ
  secret_access_key:
    secure: aOPERPkfN0RN6MzTIW7AYT9VRiHNM5RBXAkHOlOvpEP4XJ/x30b4nmabeF8cL+z5FiOXGICx5K0yHS90vHhXIAgo4nQUjxMwq2lxM195U/ofhdxBbSxPDsT8eV9L8DJ06a3suuRUANHYCYwz0sPh+cDkhf5bUIBISwy1tsd/g5XvmaOhTMdraGaBsta4iabatlyZ+c+d2tWgHTOUamnZS+8D6xhxCdudET15f5l22C4wbyFqDh8geDrGGa19jLJ3IEYYPCZBWLqvhnspx3FDhdMdMDgH7RNgqkEnK2HBUW5xIlHyNbE+tKIdlr0qtv4ZhR1pw1SeuOGiRuhY+V6cGhOXTY/P1LoCI8PQiv3jxq98eCVmp9BfWyzTtDxpo5ACJYcyrF6ObTN54KAJ9hQxhb5EIdYB6f/Jbwu5pYw7yX0NXlYim0aDXamEP9xLh1Hju2Zh9b3jBFfdBKEvpjUy+7vdZEj2PHYH3+zWmtXs8mLM/Qg4YL/fP3PFS5DTEYQxl6osOfCMo/tA1OcJtWzkiTAOCkVKfJi+rWjsde3Nx8D/5ENdV8a+QtFEARHdZBgu5H+VHrv27HVNuotX7UafySi3cIUnt9SjXUD7W4230SY1KVPyOhSEfZDLwJKM6jKBUBr7MjZ5FIRMLY9RO5ig/Apk2UQHz73lgMr0u28vfMk=
  bucket: files.gridbugs.org
  local-dir: scripts
  acl: public_read
