language: rust
matrix:
  include:
  - os: linux
    rust: stable
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
  - os: osx
    rust: stable
  allow_failures:
  - rust: nightly
dist: trusty
script:
- scripts/build.sh
deploy:
  provider: s3
  access_key_id: AKIAJTZWT26OECTU2UVQ
  secret_access_key:
    secure: hAWIWKWlYL7xoTPfrtPiOIP2PVxmzNTQJVwEIkfS+xCBqgt/FwsekNXFaK+wgRIJhZ1CkdI/nspEU8dmut8rigPoe1DzW5690s+kW9BCbKF8ID6JjMqP5i3gaF4WCw/kV5YPYvnINbWRXQuOKMqrCG3H7G5uagJBFpmVor51IK1NAWwTpdbIS2c/6259FLzMNEh9MZZzTNT+Rgp3g1FaIiN4M24ooFcWaYXAqB9aPZ1zNhXU34AAHkLhMDXhPFzUOdmBxro3zxR0cqWGLtvmJeGpFTzS1HgsKhKxbAyBriX+vFxfIhQhUNzomO4GNXrg1M0KdksrOXPmbX9XzsoVdS4P1haUQ/X9oHoWNs6aZHB+tH3/WEvOVSlrQ+bhLLO5Iz2sXXA4KoW4otU80IiNOFxhJ4aKwBy5fabNorTvq1VIJJ/owaXAUjYQnGjsdvi1L99DKlAwJrCEAsBbPifEATZyIR7TL6f+CGuLvNhDCxpS51VK9whyJwNBtJ7HhlkEDqjLg4o/Omy9R4ugrn9udDSNj95zPbPbv4+GzOLrWU/lBrZTYOpT/Ux55kiDpdQ3oJPyxR8TECdBpRt28YHo5jwWPxdJivJp2CUlpTFfdlerWnnmmDp8PW8gNhGOB1SmZcC9HlvqJoLy/fpEVavmY7bJoPytcpCQg9yEipyyQhQ=
  bucket: files.gridbugs.org
  region: ap-southeast-2
  local-dir: uploads
  acl: public_read
  skip_cleanup: true
  on:
      all_branches: true
      repo: stevebob/meters-below-the-ground
      condition: "$TRAVIS_RUST_VERSION = stable"

