[package]
name = "punchcards"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
append = "0.1"
cgmath = { version = "0.16", features = ["serde"] }
direction = "0.2"
enum_primitive = "0.1"
entity_store_helper = "0.3"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
entity_store_code_gen = "0.3"
