[package]
name = "meters_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.4"
meters_prototty = { path = "../prototty" }
prototty = "0.18"
prototty_wasm = "0.18"
