[package]
name = "meters_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.6"
meters_prototty = { path = "../prototty" }
prototty = "0.21"
prototty_wasm = "0.21"
