[package]
name = "punchcards_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
punchcards_prototty = { path = "../prototty" }
prototty = "0.12"
prototty_wasm = "0.12"
