[package]
name = "punchcards_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.4"
punchcards_prototty = { path = "../prototty" }
prototty = "0.15"
prototty_wasm = "0.15"
