[package]
name = "punchcards_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
punchcards = { path = "../punchcards" }
prototty = "0.16"
prototty_common = "0.16"
direction = "0.8"
