[package]
name = "meters_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
itertools = "0.7"
meters = { path = "../meters" }
prototty = "0.17"
prototty_common = "0.17"
direction = "0.14"
