[package]
name = "punchcards_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
punchcards = { path = "../punchcards" }
prototty = { path = "/home/steve/src/prototty/prototty" }
prototty_common = { path = "/home/steve/src/prototty/common" }
direction = "0.2"
