id_width = 16
spatial_hash_key = 'coord'

[components]
coord = { type = '::grid_2d::Coord', storage = 'vector' }
solid = { storage = 'vector' }
collider = { storage = 'vector' }
player = { storage = 'btree' }
tile_info = { type = '::tile_info::TileInfo', storage = 'vector' }
npc = { storage = 'btree' }
hit_points = { type = 'i32', storage = 'hash' }
punch = { storage = 'hash' }
stairs = { storage = 'btree' }
exit = { storage = 'btree' }
slide_direction = { type = '::direction::CardinalDirection', storage = 'hash' }
bullet = { storage = 'hash' }
health_meter = { type = '::meter::Meter', storage = 'hash' }
gun_ammo_meter = { type = '::meter::Meter', storage = 'hash' }

[spatial_hash]
solid_count = { component = 'solid', aggregate = 'count' }
player_count = { component = 'player', aggregate = 'count' }
npc_set = { component = 'npc', aggregate = 'set' }
stairs_count = { component = 'stairs', aggregate = 'count' }
exit_count = { component = 'exit', aggregate = 'count' }
