[package]
name = "punchcards_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
punchcards_prototty = { path = "../prototty" }
prototty = "0.13"
prototty_unix = "0.13"
