[package]
name = "meters_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.6"
meters_prototty = { path = "../prototty" }
prototty_unix = { version = "0.22", features = ["storage"] }
