[package]
name = "punchcards_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
punchcards_prototty = { path = "../prototty" }
prototty = "0.14"
prototty_glutin = "0.14"
prototty_file_storage = "0.14"
