[package]
name = "meters_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.6"
meters_prototty = { path = "../prototty" }
prototty = "0.21"
prototty_glutin = "0.21"
prototty_file_storage = "0.21"
