[package]
name = "punchcards_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
punchcards_prototty = { path = "../prototty" }
prototty = "0.12"
prototty_glutin = "0.12"
