[package]
name = "punchcards"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
append = "0.1"
cgmath = { version = "0.16", features = ["serde"] }
direction = "0.10"
enum_primitive = "0.1"
entity_store_helper = "0.7"
grid_search = "0.5"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
entity_store_code_gen = "0.7"
