id_width = 16
spatial_hash_key = 'coord'

[components]
coord = { type = '::grid_2d::Coord', storage = 'vector' }
solid = { storage = 'vector' }
collider = { storage = 'vector' }
player = { storage = 'btree' }
tile_info = { type = '::tile_info::TileInfo', storage = 'vector' }
card = { type = '::card::Card', storage = 'btree' }
npc = { storage = 'btree' }
hit_points = { type = 'i32', storage = 'hash' }
punch = { storage = 'hash' }

[spatial_hash]
solid_count = { component = 'solid', aggregate = 'count' }
player_count = { component = 'player', aggregate = 'count' }
card_set = { component = 'card', aggregate = 'set' }
npc_set = { component = 'npc', aggregate = 'set' }
